import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport: { width: 390, height: 664 } });
await p.goto("http://localhost:4321/", { waitUntil: "networkidle" });
await p.click(".nav-menu-btn");
await p.waitForTimeout(500);
await p.screenshot({ path: "shots/y-m-menu.png" });
const inert = await p.evaluate(() => [document.getElementById("nav-sheet").inert, getComputedStyle(document.getElementById("nav-sheet")).opacity]);
console.log("menu open:", inert);
await p.click(".nav-menu-btn");
await p.waitForTimeout(500);
console.log("menu closed:", await p.evaluate(() => [document.getElementById("nav-sheet").inert, getComputedStyle(document.getElementById("nav-sheet")).visibility]));
const d = await b.newPage({ viewport: { width: 1440, height: 900 } });
await d.goto("http://localhost:4321/pris/", { waitUntil: "networkidle" });
await d.evaluate(() => { document.documentElement.style.scrollBehavior = "auto"; document.getElementById("fragor").scrollIntoView(); });
await d.waitForTimeout(600);
await d.click(".faq details:first-of-type summary");
await d.waitForTimeout(500);
await d.screenshot({ path: "shots/y-d-faq.png" });
await b.close();
