import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport: { width: 390, height: 664 } });
await p.goto("http://localhost:4321/", { waitUntil: "networkidle" });
await p.waitForTimeout(1500);
await p.click(".nav-menu-btn");
await p.waitForTimeout(300);
await p.screenshot({ path: "shots/menu.png" });
await p.click(".nav-menu-btn");
await p.evaluate(() => document.getElementById("inside").scrollIntoView({block:"start",behavior:"instant"}));
await p.waitForTimeout(1600);
await p.screenshot({ path: "shots/inside-m.png" });
const d = await b.newPage({ viewport: { width: 1440, height: 900 } });
await d.goto("http://localhost:4321/", { waitUntil: "networkidle" });
await d.evaluate(() => document.getElementById("inside").scrollIntoView({block:"start",behavior:"instant"}));
await d.waitForTimeout(1800);
await d.screenshot({ path: "shots/inside-d.png" });
await d.goto("http://localhost:4321/pris/", { waitUntil: "networkidle" });
await d.waitForTimeout(2600);
await d.screenshot({ path: "shots/pris-d.png" });
await b.close();
