import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport: { width: 390, height: 664 } });
await p.goto("http://localhost:4321/", { waitUntil: "networkidle" });
await p.waitForTimeout(2800);
await p.screenshot({ path: "shots/m-hero.png" });
await p.click(".nav-menu-btn");
await p.waitForTimeout(400);
await p.screenshot({ path: "shots/m-menu.png" });
const d = await b.newPage({ viewport: { width: 1440, height: 900 } });
await d.goto("http://localhost:4321/", { waitUntil: "networkidle" });
await d.waitForTimeout(2800);
await d.screenshot({ path: "shots/d-hero.png" });
await d.evaluate(() => document.getElementById("sprak").scrollIntoView({ block: "start", behavior: "instant" }));
await d.waitForTimeout(1800);
await d.screenshot({ path: "shots/d-sprak.png" });
await b.close();
